---
deployment:
  tasks:
    - export DEPLOYPATH1=/home2/stisipolrh/portalekampus3.stisipolrajahaji.ac.id/
    - /bin/rm -rf $DEPLOYPATH1/css
    - /bin/rm -rf $DEPLOYPATH1/js
    - /bin/cp -R frontend/dist/* $DEPLOYPATH1
    - /bin/cp -R frontend/dist/.htaccess $DEPLOYPATH1
    - export DEPLOYPATH2=/home2/stisipolrh/api.stisipolrajahaji.ac.id/
    - /bin/rm -rf $DEPLOYPATH2/app
    - /bin/rm -rf $DEPLOYPATH2/database
    - /bin/cp -R backend/* $DEPLOYPATH2
    - /usr/bin/git push origin master -u
    - /usr/bin/git push origin master -u
